## Datas
---
| **Column Name**     | **Description**                                                                 |
|---------------------|---------------------------------------------------------------------------------|
| `Order ID`          | A unique ID for each order placed.                                             |
| `Order Date`        | The date on which the order was placed.                                        |
| `Customer Name`     | Name of the customer placing the order.                                        |
| `Country`           | The country to which the customer belongs.                                     |
| `State`             | The state to which the customer belongs from the country.                      |
| `City`              | Detail about the city in which the customer resides.                           |
| `Region`            | Contains the region details.                                                   |
| `Segment`           | The ordered product belongs to what segment?                                   |
| `Ship Mode`         | The mode of shipping of the order to the customer’s location.                  |
| `Category`          | Contains the details about what category the product belongs to.              |
| `Sub-category`      | Contains the details about what sub-category the product belongs to.           |
| `Product Name`      | The name of the product ordered by the customer.                               |
| `Discount`          | The discount applicable on a product.                                          |
| `Sales`             | The actual sales happened for a particular order.                              |
| `Profit`            | Profit earned on order.                                                        |
| `Quantity`          | The total quantity of the product ordered in a single order.                   |
| `Feedback`          | The feedback given by the customer on the complete shopping experience.        |
|                     | If feedback is provided, then `TRUE`. If not, then `FALSE`.                    |

In [3]:
import pandas as pd
from datetime import datetime

In [5]:
df = pd.read_excel(r"C:\Users\ASUS\Downloads\superstore.xlsx")

In [7]:
df.shape

(8047, 17)

In [8]:
df

,Order ID,Order Date,Customer Name,Country,State,City,Region,Segment,Ship Mode,Category,Sub-Category,Product Name,Discount,Sales,Profit,Quantity,Feedback?
0,BN-2011-7407039,2011-01-01,Ruby Patel,Sweden,Stockholm,Stockholm,North,Home Office,Economy Plus,Office Supplies,Paper,"Enermax Note Cards, Premium",0.5,45,-26,3,False
1,AZ-2011-9050313,2011-01-03,Summer Hayward,United Kingdom,England,Southport,North,Consumer,Economy,Furniture,Bookcases,"Dania Corner Shelving, Traditional",0.0,854,290,7,True
2,AZ-2011-6674300,2011-01-04,Devin Huddleston,France,Auvergne-Rhône-Alpes,Valence,Central,Consumer,Economy,Office Supplies,Art,"Binney & Smith Sketch Pad, Easy-Erase",0.0,140,21,3,True
3,BN-2011-2819714,2011-01-04,Mary Parker,United Kingdom,England,Birmingham,North,Corporate,Economy,Office Supplies,Art,"Boston Markers, Easy-Erase",0.5,27,-22,2,True
4,BN-2011-2819714,2011-01-04,Mary Parker,United Kingdom,England,Birmingham,North,Corporate,Economy,Office Supplies,Storage,"Eldon Folders, Single Width",0.5,17,-1,2,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8042,AZ-2014-766953,2014-12-31,Jose Gambino,United Kingdom,England,Maidenhead,North,Corporate,Economy,Furniture,Bookcases,"Ikea Stackable Bookrack, Traditional",0.0,245,91,2,True
8043,BN-2014-4140795,2014-12-31,Daniel Hamilton,Netherlands,North Brabant,Eindhoven,Central,Home Office,Economy Plus,Office Supplies,Art,"BIC Pencil Sharpener, Fluorescent",0.5,30,-10,2,False
8044,BN-2014-4140795,2014-12-31,Daniel Hamilton,Netherlands,North Brabant,Eindhoven,Central,Home Office,Economy Plus,Office Supplies,Binders,"Avery Binder Covers, Recycled",0.5,23,-6,4,True
8045,BN-2014-4140795,2014-12-31,Daniel Hamilton,Netherlands,North Brabant,Eindhoven,Central,Home Office,Economy Plus,Technology,Machines,"StarTech Phone, Red",0.5,108,-19,3,False
8046,AZ-2014-766953,2014-12-31,Jose Gambino,United Kingdom,England,Maidenhead,North,Corporate,Economy,Technology,Phones,"Motorola Audio Dock, VoIP",0.0,867,251,5,False

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8047 entries, 0 to 8046
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       8047 non-null   object
 1   Order Date     8047 non-null   datetime64[ns]
 2   Customer Name  8047 non-null   object
 3   Country        8047 non-null   object
 4   State          8047 non-null   object
 5   City           8047 non-null   object
 6   Region         8047 non-null   object
 7   Segment        8047 non-null   object
 8   Ship Mode      8047 non-null   object
 9   Category       8047 non-null   object
 10  Sub-Category   8047 non-null   object
 11  Product Name   8047 non-null   object
 12  Discount       8047 non-null   float64
 13  Sales          8047 non-null   int64
 14  Profit         8047 non-null   int64
 15  Quantity       8047 non-null   int64
 16  Feedback?      8047 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(3), object(11)
memory usage: 1013.9+ KB

In [10]:
df.describe()

,Order Date,Discount,Sales,Profit,Quantity
count,8047,8047.000000,8047.000000,8047.000000,8047.000000
mean,2013-04-19 12:25:40.748104704,0.110047,291.845657,35.198211,3.772089
min,2011-01-01 00:00:00,0.000000,3.000000,-3060.000000,1.000000
25%,2012-06-08 00:00:00,0.000000,48.000000,1.000000,2.000000
50%,2013-06-11 00:00:00,0.000000,117.000000,14.000000,3.000000
75%,2014-04-30 00:00:00,0.100000,313.000000,47.000000,5.000000
max,2014-12-31 00:00:00,0.850000,6517.000000,2476.000000,14.000000
std,NaN,0.181773,485.212156,178.125844,2.203369

In [11]:
pd.DataFrame({
    'feature': df.columns.values,
    'data_type': df.dtypes.values,
    'missing_values': df.isnull().sum(),
    'missing_percentage': df.isnull().sum() / df.shape[0] * 100,
    'unique_values': df.nunique().values,
    'sample_unique': [df[col].unique() for col in df.columns]
    }).round(3)

,feature,data_type,missing_values,missing_percentage,unique_values,sample_unique
Order ID,Order ID,object,0,0.0,4117,"[BN-2011-7407039, AZ-2011-9050313, AZ-2011-667..."
Order Date,Order Date,datetime64[ns],0,0.0,1214,"[2011-01-01 00:00:00, 2011-01-03 00:00:00, 201..."
Customer Name,Customer Name,object,0,0.0,792,"[Ruby Patel, Summer Hayward, Devin Huddleston,..."
Country,Country,object,0,0.0,15,"[Sweden, United Kingdom, France, Italy, Austri..."
State,State,object,0,0.0,127,"[Stockholm, England, Auvergne-Rhône-Alpes, Pro..."
City,City,object,0,0.0,999,"[Stockholm, Southport, Valence, Birmingham, Ec..."
Region,Region,object,0,0.0,3,"[North, Central, South]"
Segment,Segment,object,0,0.0,3,"[Home Office, Consumer, Corporate]"
Ship Mode,Ship Mode,object,0,0.0,4,"[Economy Plus, Economy, Priority, Immediate]"
Category,Category,object,0,0.0,3,"[Office Supplies, Furniture, Technology]"
Sub-Category,Sub-Category,object,0,0.0,17,"[Paper, Bookcases, Art, Storage, Fasteners, Bi..."
Product Name,Product Name,object,0,0.0,1810,"[Enermax Note Cards, Premium, Dania Corner She..."
Discount,Discount,float64,0,0.0,14,"[0.5, 0.0, 0.1, 0.6, 0.4, 0.2, 0.65, 0.15, 0.7..."
Sales,Sales,int64,0,0.0,1248,"[45, 854, 140, 27, 17, 90, 207, 155, 33, 716, ..."
Profit,Profit,int64,0,0.0,845,"[-26, 290, 21, -22, -1, 77, 36, 2, 143, -1012,..."
Quantity,Quantity,int64,0,0.0,14,"[3, 7, 2, 4, 1, 6, 5, 11, 8, 10, 12, 9, 14, 13]"
Feedback?,Feedback?,bool,0,0.0,2,"[False, True]"

In [12]:
df[df.duplicated()]

,Order ID,Order Date,Customer Name,Country,State,City,Region,Segment,Ship Mode,Category,Sub-Category,Product Name,Discount,Sales,Profit,Quantity,Feedback?
2543,AZ-2012-5907386,2012-08-29,Louie Knight,Belgium,Antwerp,Mechelen,Central,Consumer,Economy,Office Supplies,Art,"Sanford Pens, Fluorescent",0.0,37,10,3,False
4066,AZ-2013-5637964,2013-06-14,Cynthia Zielinski,Spain,Madrid,Madrid,South,Home Office,Economy,Office Supplies,Binders,"Wilson Jones 3-Hole Punch, Economy",0.0,84,28,3,True

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df = df.drop_duplicates().reset_index(drop=True)

In [15]:
df

,Order ID,Order Date,Customer Name,Country,State,City,Region,Segment,Ship Mode,Category,Sub-Category,Product Name,Discount,Sales,Profit,Quantity,Feedback?
0,BN-2011-7407039,2011-01-01,Ruby Patel,Sweden,Stockholm,Stockholm,North,Home Office,Economy Plus,Office Supplies,Paper,"Enermax Note Cards, Premium",0.5,45,-26,3,False
1,AZ-2011-9050313,2011-01-03,Summer Hayward,United Kingdom,England,Southport,North,Consumer,Economy,Furniture,Bookcases,"Dania Corner Shelving, Traditional",0.0,854,290,7,True
2,AZ-2011-6674300,2011-01-04,Devin Huddleston,France,Auvergne-Rhône-Alpes,Valence,Central,Consumer,Economy,Office Supplies,Art,"Binney & Smith Sketch Pad, Easy-Erase",0.0,140,21,3,True
3,BN-2011-2819714,2011-01-04,Mary Parker,United Kingdom,England,Birmingham,North,Corporate,Economy,Office Supplies,Art,"Boston Markers, Easy-Erase",0.5,27,-22,2,True
4,BN-2011-2819714,2011-01-04,Mary Parker,United Kingdom,England,Birmingham,North,Corporate,Economy,Office Supplies,Storage,"Eldon Folders, Single Width",0.5,17,-1,2,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,AZ-2014-766953,2014-12-31,Jose Gambino,United Kingdom,England,Maidenhead,North,Corporate,Economy,Furniture,Bookcases,"Ikea Stackable Bookrack, Traditional",0.0,245,91,2,True
8041,BN-2014-4140795,2014-12-31,Daniel Hamilton,Netherlands,North Brabant,Eindhoven,Central,Home Office,Economy Plus,Office Supplies,Art,"BIC Pencil Sharpener, Fluorescent",0.5,30,-10,2,False
8042,BN-2014-4140795,2014-12-31,Daniel Hamilton,Netherlands,North Brabant,Eindhoven,Central,Home Office,Economy Plus,Office Supplies,Binders,"Avery Binder Covers, Recycled",0.5,23,-6,4,True
8043,BN-2014-4140795,2014-12-31,Daniel Hamilton,Netherlands,North Brabant,Eindhoven,Central,Home Office,Economy Plus,Technology,Machines,"StarTech Phone, Red",0.5,108,-19,3,False
8044,AZ-2014-766953,2014-12-31,Jose Gambino,United Kingdom,England,Maidenhead,North,Corporate,Economy,Technology,Phones,"Motorola Audio Dock, VoIP",0.0,867,251,5,False

In [16]:
df.isna().sum()

Order ID         0
Order Date       0
Customer Name    0
Country          0
State            0
City             0
Region           0
Segment          0
Ship Mode        0
Category         0
Sub-Category     0
Product Name     0
Discount         0
Sales            0
Profit           0
Quantity         0
Feedback?        0
dtype: int64

In [18]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8040    False
8041    False
8042    False
8043    False
8044    False
Length: 8045, dtype: bool

In [19]:
df.dtypes

Order ID                 object
Order Date       datetime64[ns]
Customer Name            object
Country                  object
State                    object
City                     object
Region                   object
Segment                  object
Ship Mode                object
Category                 object
Sub-Category             object
Product Name             object
Discount                float64
Sales                     int64
Profit                    int64
Quantity                  int64
Feedback?                  bool
dtype: object

In [20]:
df.describe()

,Order Date,Discount,Sales,Profit,Quantity
count,8045,8045.000000,8045.000000,8045.000000,8045.000000
mean,2013-04-19 12:57:32.778123008,0.110075,291.903170,35.202237,3.772281
min,2011-01-01 00:00:00,0.000000,3.000000,-3060.000000,1.000000
25%,2012-06-08 00:00:00,0.000000,48.000000,1.000000,2.000000
50%,2013-06-11 00:00:00,0.000000,117.000000,14.000000,3.000000
75%,2014-04-30 00:00:00,0.100000,313.000000,47.000000,5.000000
max,2014-12-31 00:00:00,0.850000,6517.000000,2476.000000,14.000000
std,NaN,0.181787,485.258616,178.147747,2.203610